### ISSUE TITLE
Dates are converted wrong

### ISSUE THREAD

**Issue by hathix** [nickboucher/nova#12]
![screen shot 2017-02-01 at 7 48 51 pm](https://cloud.githubusercontent.com/assets/728084/22532789/8197c0ac-e8b7-11e6-9425-392dd3038a8a.png)

I entered 01/01/2017 as the start and end date on Qualtrics, yet Nova thinks I entered 12/31/2016. Maye something wrong with time zones?

**Comment by nickboucher** [comment]
It was in UTC -- now corrected
