### ISSUE TITLE
Nit: ensure no checkboxes are missed

### ISSUE THREAD

**Issue by hathix** [nickboucher/nova#15]
![screen shot 2017-02-01 at 7 59 36 pm](https://cloud.githubusercontent.com/assets/728084/22532967/fdd4b9d0-e8b8-11e6-868c-18e89caa1c16.png)

Once the interview happens, "interview scheduled" should still be checked.

**Comment by nickboucher** [comment]
This is actually correct behavior: when we were testing this feature, we didn't use nova to test "schedule" interviews. If we did, then this would have automatically been checked.
