### ISSUE TITLE
Include UC logo on site

### ISSUE THREAD

**Issue by hathix** [nickboucher/nova#2]
Currently, the UC logo and name is in the `<title>`, but I think we should include it on the page itself (for instance, in the header bar or the footer) so that users know what exactly it is. It's also great publicity for the UC!

**Comment by nickboucher** [comment]
Added UC Logo to homepage. Non-UC (i.e. non-authenticated) users won't see navbar (and there is no footer), so for the time I think this will suffice until we do a UI overhaul.

**Comment by nickboucher** [comment]
When I add a public-facing search interface, I will plan to include the UC logo.
